drivers: rtl8x: Hardcore some headers path
Log:
fatal error: drv_types.h: No such file or directory
fatal error: halrf/halrf_psd.h: No such file or directory
fatal error: platform_ops.h: No such file or directory

Change-Id: 2057669d4a1385b73c35569612348cfafe76a5fa
Signed-off-by: TogoFire <togofire@mailfence.com>
(cherry picked from commit 0ceb016f477a424dd5911367225623ecef56f27b)
Signed-off-by: Madara273 <ravenhoxs@gmail.com>