qca-wifi-host-cmn: Fix snprintf size argument
Fixes:
drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/htc/htc_recv.c:50:4:
error: 'snprintf' will always be truncated; specified size is 2,
but format string expands to at least 5 [-Werror,-Wfortify-source]
   50 |                         A_SNPRINTF(byteOffsetStr, sizeof(byteOffset), "%4.4X",

drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/htc/htc_recv.c:59:3:
error: 'snprintf' will always be truncated; specified size is 2,
but format string expands to at least 5 [-Werror,-Wfortify-source]
   59 |                 A_SNPRINTF(byteOffsetStr, sizeof(byteOffset), "%4.4X",
2 errors generated.

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: Iad113a27384b824e09f199fbbecc8239b1922d73
(cherry picked from commit 2fe223efbf4be4188e63573b853d779721f87c5c)
Signed-off-by: Madara273 <ravenhoxs@gmail.com>